server:
  port: 8080
 
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    register-with-eureka: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: region-provider-module
        uri: lb://REGION-PROVIDER
        predicates:
        - Path=/api/region/**

      - id: vm-provider-module
        uri: lb://VM-PROVIDER
        predicates:
        - Path=/api/vehicleManufacturer/**

      - id: insurance-premium-provider-module
        uri: lb://INSURANCE-PREMIUM-PROVIDER
        predicates:
        - Path=/api/premium/**
