server:
  port: 8091
  error:
    include-stacktrace: never

spring:
  application:
    name: region-provider
  datasource:
    url: jdbc:mongodb://mongo:27027/
    username: admin
    password: admin
  servlet:
    multipart:
      maxFileSize: 128MB
      maxRequestSize: 128MB
  http:
    multipart:
      enabled: true
  data:
    mongodb:
      auto-index-creation: true
  
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-service:8761/eureka}
    enabled: true
    register-with-eureka: true
